name: Data Refresh

on: 
  #push:
  schedule:
    - cron:  '5 4 * 1 *'
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        R: [ '3.5.3', '3.6.1' ]
    name: refresh the dashboard
    steps:
      #- uses: actions/checkout@v1
      #    with: cdash
      #- uses: r-lib/actions/setup-r@v1
      #- uses: r-lib/actions/setup-pandoc@v1
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: cdash
      #
      - name: Set ENV
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.R }}
      - name: pandoc
        uses: r-lib/actions/setup-pandoc@v1
      - name: Install CRAN packages
        run: |
          cd ./cdash/
          sh dependency.sh > log.txt 2>&1
          Rscript -e 'print("hello")'
      - name: Run The script
        run: |
          cd ./cdash/
          #Rscript -e 'rmarkdown::render("india.Rmd")'
          #sh run.sh >> log.txt 2>&1
          dtt=`date`
          echo "${dtt}" >> processed.md
          bash make-rdme.sh >> log.txt 2>&1

      - name:  push to git
        run: |
          cd ./cdash/ 
          git remote -v
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git status
          git diff-index --quiet HEAD || git commit -m "Update json" -a
          git push
