name: Data Collector
on:
  push:
  schedule:
    - cron:  '*/30 * * * *'
#


jobs:
  extract_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: data repo
        uses: actions/checkout@v2
        with:
          repository: dsjena/test-data
          path: data
      - name: Set up me python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      #- name: Install dependencies
        #run: |
          #python -m pip install --upgrade pip
          #pip install -r requirements.txt
        
      #- name: main sec
      #  uses: ./main/
      #  id: code
      - name: actual run
        run: |
          cd main
          ls -rtl
          sh run.sh
          
      - name: commit main
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: update data

      #- name: Update Data
      #  uses: ./data/
      #  id: data
        
      - name: actual data
        run: |
          cd ../data/
          cp -r ../main/csv .
          
      - name: commit data
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: update data
