name: Data Refresh

on: [push]
  #schedule:
    # * is a special character in YAML so you have to quote this string
   # - cron:  '0 */6 * * *'
jobs:
  build:
    name: refresh the dashboard
    runs-on: macos-latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
      - name: set_R
        uses: r-lib/actions/setup-r@master
        with:
          repository: ${{ github.repository }}
          ref: 'master'
          token: ${{ github.token }}
          clean: 'true'
          fetch-depth: '1'
      - name: Install CRAN packages
        run: Rscript -e "install.packages(c('devtools', 'rmarkdown', 'flexdashboard', 'dplyr', 'purrr', 'lubridate', 'plotly'))"
      - name: Run The script
        run: |
          Rscript R/readData.R
          git remote -v                                                                                                                                              git config --local user.email "action@github.com"                                                                                                          git config --local user.name "GitHub Action"                                                                                                               git add .                                                                                                                                                  git status                                                                                                                                                 git diff-index --quiet HEAD || git commit -m "Update json" -a                                                                                              git push         
